version: '3.8'


services:
  auth_service_1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
    environment:
      - FLASK_ENV=development
    networks:
      auth-network:
        ipv4_address: 172.19.0.2

  auth_service_2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
    environment:
      - FLASK_ENV=development
    networks:
      auth-network:
        ipv4_address: 172.19.0.3

networks:
  auth-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24

