version: '3.8'

services:
  auth_service_3:
    build:
      context: ./auth-page-3/backend
      dockerfile: Dockerfile
    ports:
      - "5044:7000"
    volumes:
      - ./auth-page-3/backend:/app
      - ./auth-page-3/frontend:/app/frontend
    environment:
      - FLASK_ENV=development
    networks:
      auth-network-2:
        ipv4_address: 172.15.0.2

  auth_service_4:
    build:
      context: ./auth-page-3/backend
      dockerfile: Dockerfile
    ports:
      - "5045:8000"
    volumes:
      - ./auth-page-4/backend:/app
      - ./auth-page-4/frontend:/app/frontend
    environment:
      - FLASK_ENV=development
    networks:
      auth-network-2:
        ipv4_address: 172.15.0.3

  haproxy-2:
    image: haproxy:2.6
    ports:
      - "8082:80"
    volumes:
      - ./haproxy-2.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      auth-network-2:
        ipv4_address: 172.15.0.10

networks:
  auth-network-2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.15.0.0/24