version: '3.8'

networks:
  auth-network-2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24

services:
  auth_service_3:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5003:6000"
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
    environment:
      - FLASK_ENV=development
    networks:
      auth-network-2:
        ipv4_address: 172.25.0.2

  auth_service_4:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5004:6000"
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
    environment:
      - FLASK_ENV=development
    networks:
      auth-network-2:
        ipv4_address: 172.25.0.3
