version: '3.8'

networks:
  auth-network-2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
  haproxy-network:
    external: true

services:
  auth_service_3:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5003:6000"
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
    environment:
      - FLASK_ENV=development
    networks:
      auth-network-2:
        ipv4_address: 172.25.0.2

  auth_service_4:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5004:6000"
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
    environment:
      - FLASK_ENV=development
    networks:
      auth-network-2:
        ipv4_address: 172.25.0.3

  haproxy-2:
    image: haproxy:2.6
    ports:
      - "8082:80"
    volumes:
      - ./haproxy-2.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - auth-network-2
      - haproxy-network

  keepalived:
    image: osixia/keepalived:latest
    volumes:
      - ./keepalived/keepalived.conf:/etc/keepalived/keepalived.conf
    network_mode: "host"
    privileged: true
