version: '3.8'

services:
  auth_service_3:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5003:6000"
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
    environment:
      - FLASK_ENV=development

  auth_service_4:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5004:6000"
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
    environment:
      - FLASK_ENV=development