version: '3.8'

services:
  auth_service_3:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "6003:6000"
    volumes:
      - ./backend:/backend
    environment:
      - FLASK_ENV=development

  auth_service_4:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "6004:6000"
    volumes:
      - ./backend:/backend
    environment:
      - FLASK_ENV=development