version: '3.8'

services:
  auth_service_1:
    build:
      context: ./auth-page/backend
      dockerfile: Dockerfile
    ports:
      - "5011:5000"
    volumes:
      - ./auth-page/backend:/app
      - ./auth-page/frontend:/app/frontend
    environment:
      - FLASK_ENV=development
    networks:
      auth-network-1:
        ipv4_address: 172.19.0.2

  auth_service_2:
    build:
      context: ./auth-page-2/backend
      dockerfile: Dockerfile
    ports:
      - "5012:5000"
    volumes:
      - ./auth-page-2/backend:/app
      - ./auth-page-2/frontend:/app/frontend
    environment:
      - FLASK_ENV=development
    networks:
      auth-network-2:
        ipv4_address: 172.20.0.3

  haproxy-1:
    image: haproxy:2.6
    ports:
      - "8081:80"
    volumes:
      - ./haproxy-1.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      auth-network-1:
        ipv4_address: 172.19.0.10
      auth-network-2:
        ipv4_address: 172.20.0.10

networks:

  auth-network-1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
        
  auth-network-2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24