version: '3.8'

services:
  auth_service_1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5044:8000"
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
    environment:
      - FLASK_ENV=development
    networks:
      auth-network-1:
        ipv4_address: 172.15.0.2

  auth_service_2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5045:8000"
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
    environment:
      - FLASK_ENV=development
    networks:
      auth-network-1:
        ipv4_address: 172.15.0.3

  haproxy-1:
    image: haproxy:2.6
    ports:
      - "8084:80"
    volumes:
      - ./haproxy-4.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      auth-network-1:
        ipv4_address: 172.15.0.10

networks:
  auth-network-1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.15.0.0/24